### ISSUE TITLE
API key in OpenAI.NET.Playground.Web/wwwroot/appsettings.json

### ISSUE THREAD

**Issue by ADefWebserver** [lucabriguglia/Cledev.OpenAI#1]
Putting the API key in this location would cause it to end up in the web browser cache and completely exposed if deployed to the web.

Having that key leaked would be very bad and that mistake could be made by a novice user. If anyone deployed the app to the public web it would be a disaster (because the hackers would be looking for this).

Perhaps use Blazor Server or Blazor MAUI rather than Blazor WebAssembly so that the key could be placed in appsettings.json (or secrets file)?

**Comment by lucabriguglia** [comment]
I'm aware of the problem, the idea was that the playground would have been used only locally and I was keen to use web assembly. But you are right, it may be better to use something else. Blazor MAUI is tempting.
